### ISSUE TITLE
1.20.1 服务器内无法使用

### ISSUE THREAD

**Issue by ddaodan** [SmallJiu/Email#4]
百科的介绍里说有三种方式打开邮箱，
聊天栏右上角：没有看到
创造物品栏右下角：夸克和路标mod在那个位置加了一个管理员用品栏，挡住了
![image](https://github.com/SmallJiu/Inbox/assets/40017293/44511dac-091b-4023-8fa8-321f4e8b8bc3)

生存物品栏的玩家模型左上角：被饰品栏挡住了
![image](https://github.com/SmallJiu/Inbox/assets/40017293/3416704e-b510-40bf-a124-38e263e4c281)
用fancymenu修改了一下按钮的位置，点击后没有任何反应，服务器后台报错：
```
[13:53:45 ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.AbstractContainerMenu.setTitle(net.minecraft.network.chat.Component)" because "c" is null
        at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:211) ~[forge-1.20.1-47.2.20-universal.jar%23505!/:?]
        at cat.jiu.email.ui.GuiHandler.openGui(GuiHandler.java:144) ~[Inbox-1.20.1-1.0.1.jar%23450!/:1.20.1-1.0.1]
        at cat.jiu.email.net.msg.MsgOpenGui.lambda$handler$0(MsgOpenGui.java:31) ~[Inbox-1.20.1-1.0.1.jar%23450!/:1.20.1-1.0.1]
        at cat.jiu.email.net.msg.MsgOpenGui.lambda$onServerTick$1(MsgOpenGui.java:44) ~[Inbox-1.20.1-1.0.1.jar%23450!/:1.20.1-1.0.1]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at cat.jiu.email.net.msg.MsgOpenGui.onServerTick(MsgOpenGui.java:41) ~[Inbox-1.20.1-1.0.1.jar%23450!/:1.20.1-1.0.1]
        at cat.jiu.email.net.msg.__MsgOpenGui_onServerTick_ServerTickEvent.invoke(.dynamic) ~[Inbox-1.20.1-1.0.1.jar%23450!/:1.20.1-1.0.1]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23145!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23145!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23145!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:974) ~[forge-1.20.1-47.2.20-universal.jar%23505!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1070) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:902) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
```
单机能正常打开
服务端是1.20.1 mohist

**Comment by SmallJiu** [comment]
下个版本会添加三个地方的按钮的位置设置
[png](https://github.com/SmallJiu/Inbox/assets/70803028/78e617ca-801c-4b1f-8230-7e0827792914)

**Comment by SmallJiu** [comment]
聊天栏的按钮需要打开这个设置才能显示![png](https://github.com/SmallJiu/Inbox/assets/70803028/bde396d6-fb1c-43af-a171-a33622463e61)
